//
// Created by 祖国瑞 on 2022/9/24.
//

#ifndef ANDROID_VIDEOPLAYER_CODECTYPE_H
#define ANDROID_VIDEOPLAYER_CODECTYPE_H

enum CodecType {
    UNKNOWN = -2, NOT_SUPPORTED = -1, HW = 0, SW = 1
};

#endif //ANDROID_VIDEOPLAYER_CODECTYPE_H
