//
// Created by 祖国瑞 on 2022/9/7.
//

#ifndef ANDROID_VIDEOPLAYER_CONSTANTS_H
#define ANDROID_VIDEOPLAYER_CONSTANTS_H



const int DEFAULT_SAMPLE_RATE = 48000;
const int DEFAULT_CHANNELS = 2;

const int DEFAULT_VIDEO_WIDTH = 1920;
const int DEFAULT_VIDEO_HEIGHT = 1080;
const int DEFAULT_PIX_SIZE = 24; // RGB_888





#endif //ANDROID_VIDEOPLAYER_CONSTANTS_H
