//
// Created by 祖国瑞 on 2023/1/8.
//

#ifndef ANDROID_VIDEOPLAYER_FLAGS_H
#define ANDROID_VIDEOPLAYER_FLAGS_H

#define STREAM_FLAG_EOF 1
#define STREAM_FLAG_SOUGHT (1 << 1)


#endif //ANDROID_VIDEOPLAYER_FLAGS_H
