//
// Created by 祖国瑞 on 2022/12/14.
//

#ifndef ANDROID_VIDEOPLAYER_SIZEMODE_H
#define ANDROID_VIDEOPLAYER_SIZEMODE_H

enum SizeMode {
    FIT,
    SCALE_FULL,
};

#endif //ANDROID_VIDEOPLAYER_SIZEMODE_H
